name: SimpleFFA
main: me.timof121.simpleffa.MainClass
version: 0.2
api-version: 1.8.8
author: timof121
description: A simple plugin that implements a Free For All gamemode on your server!
commands:
   joinffa:
      description: Join the FFA arena lol.
      usage: /joinffa
      permission: simpleffa.join
   leaveffa:
      description: Leave FFA lmao.
      usage: /leaveffa
      permission: simpleffa.leave
